version: "3"

services:
  nginx_container:
    container_name: nginx
    image: danwhite123/nginx-image:latest
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "80:80"


  apache_container:
    container_name: apache
    image: danwhite123/apache-image:latest
    build:
      context: .
      dockerfile: Dockerfile_apache
    ports:
      - "8080:80"

