pipeline {
    agent any

    stages {

        stage('Docker version') {
            agent {
                label 'ubuntu'
            }
            steps {
                sh "echo $USER"
                sh 'sudo chmod 777 /var/run/docker.sock'
                sh 'docker version'
            }
        }

        stage('Docker version master') {
            agent {
                label 'master'
            }
            steps {
                sh "echo $USER"
                sh 'docker version'
            }
        }


        stage('Copy Host File') {
            steps {
                // Copy the host file to the pipeline workspace
                copyArtifacts(projectName: 'StablePipline', filter: '/home/ubuntu/.ssh/Task4.pem', flatten: true)

                // Move the copied file to the desired location
                sh 'cp Task4.pem /var/lib/jenkins/workspace/StablePipline/'
            }
        }

        stage('Run Ansible Playbook') {
            agent {
                label 'master'
            }
            steps {
                ansiblePlaybook(
                    playbook: 'ansible/installer_of_docker_and_jdk.yml',
                    inventory: 'ansible/hosts.txt',
                    hostKeyChecking: 'false'
                )
            }
        }
    }
}