---
- name: Install Docker and jdk
  hosts:
    - ubuntu_group
  become: true

  tasks:
    - name: Install prerequisites for Docker on Ubuntu
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG key Ubuntu
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository Ubuntu
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker on Ubuntu
      apt:
        name:
          - docker-ce
          - docker-compose
        state: latest
        update_cache: true

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add directory for jenkins
      shell:
        cmd: mkdir jenkins
      args:
        creates: jenkins

    - name: change permissions
      become: yes
      shell:
        cmd: chmod 777 jenkins/

    - name: Update apt packages and install fontconfig and OpenJDK 17
      apt:
        update_cache: yes
        name:
          - fontconfig
          - openjdk-17-jre
        state: present
